### ISSUE TITLE
Template Inhaltsbereich nutzen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#10]
Bei templates kann es sinnvoll sein, einen echten eigenen textinhalt zu setzen, statt gleich die Blogroll.

Daher würde ich vorschlagen, dass nach dem Bereich der Themenboxen und vor der Blogroll der
  content()
derjeweiligen Page gezeigt wird.
Dieser ist ja bereits eingebbar gewesen.

**Comment by cowglow** [comment]
Do you mean with the WordPress Native Search Results?

**Comment by xwolfde** [comment]
uh, sorry, forget this. this is an issue for another projekt :)
