### ISSUE TITLE
API Key und API ID

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#11]
Die API ID ist hardcodiert.
Wenn man eine eigene API key eingibt, passt das nicht zusammen. Bzw. ich erhalten aktuell keine Ergebnisse, die richtig zugeordnet werden.
Statt meine beschränkte Suche mit meiner key zu machen, wird global bei Google gesucht

**Comment by cowglow** [comment]
I've updated the Foundation class and added the ID on adapter class. Much easier to change now.

**Comment by jkphl** [comment]
@cowglow But where do you configure the API ID? In the source code only? Isn't it different for each configured GCS?
