### ISSUE TITLE
Google Rate Limit erkennen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#12]
Was passiert eigentlich, wenn wir den täglichen Freibetrag von 10000 Suchen erreichen?

**Comment by cowglow** [comment]
The response json object will contain no search results and a message that the daily limit has been reached:

[https://developers.google.com/custom-search/json-api/v1/site_restricted_api](https://developers.google.com/custom-search/json-api/v1/site_restricted_api)

**Comment by xwolfde** [comment]
So... what will we display then on our website?

**Comment by jkphl** [comment]
@xwolfde I don't think there's a way to get around a paid option.

**Comment by xwolfde** [comment]
Enhancement: Wenn Limit erreicht:
1. Suchbegriff an lokale Suche umleiten
2. Mail an Sitebetreiber (Admin) mit Hinweis.

**Comment by jkphl** [comment]
guter anhaltspunkt, danke!

**Comment by xwolfde** [comment]
bisher nicht relevant, daher ticket geschlossen.
