### ISSUE TITLE
Übersetzung fehlerhaft

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#21]
Das Backend ist nicht korrekt übersetzt (Seite ist auf lang de_DE) (abgesehen von der Warning, die auch nicht sein darf).
![2018-10-19-10-13-test8 tindu rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/47205997-da38c780-d387-11e8-843a-96184500b4c7.png)

**Comment by xwolfde** [comment]
Funktioniert auch im Frontend nicht.
![2018-10-19-11-02-test8 tindu rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/47208732-de1c1800-d38e-11e8-9ebc-293058f632b9.png)

**Comment by xwolfde** [comment]
Templates/Results/WordPressSearch-shortcode.php:

Kann so wohl kaum richtig übersetzt werden:


```
<h2>Suchergebnisse</h2>
<p class="notice-hinweis"><?= __('Es wird nur in diesem Webauftritt gesucht. Um Dokumente und Seiten aus anderen Webauftritten zu finden, nutzen Sie die jeweils dort zu findende Suchmaschine oder verwenden eine Internet-Suchmaschine.', 'fau'); ?></p>

<div id="resultStats"><?php echo sprintf(__('About %1$s results', 'rrze-search'),
```

**Comment by jkphl** [comment]
Diese Datei sollte eigentlich gar nicht im Einsatz sein, kann das sein? Wir prüfen, ob sie gelöscht werden kann!

**Comment by xwolfde** [comment]
Die wurde erfolgreich angesteiert. SPielt aber keine ROlle. AUch die Übersetzung funktioniert mit der Änderung vorhin nicht. Ich fix das selbst

**Comment by xwolfde** [comment]
gefixt

**Comment by xwolfde** [comment]
Übersetzung nun auch für die Quicklinks korrigiert
