### ISSUE TITLE
Ratefeld in Settings

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#25]
Was möge das wohl für ein Eingabefeld sein...
![2018-10-19-11-02-test8 tindu rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/47208638-a319e480-d38e-11e8-8035-4f0311466de2.png)

**Comment by jkphl** [comment]
@cowglow Vermutlich verwandt mit #21 — Lokalisierung scheint beschädigt
