### ISSUE TITLE
Settings und Darstellung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#4]
Ich hab diese Darstellung:
![image](https://user-images.githubusercontent.com/1070669/46580184-521a0000-ca20-11e8-9e44-5da5edbafeae.png)

Aber diese Settings_:
![image](https://user-images.githubusercontent.com/1070669/46580186-64943980-ca20-11e8-961c-ba92f29521fa.png)

Müsste nicht hinter jeder Suchmaschine ein Link sein?

**Comment by cowglow** [comment]
I know how this happening.
The __Google FAU CS__ instance belongs to the Google1Adapter which it's label doesn't contain the `%s` placeholder for the Datenschutz link. It's was originally setup that way, but I've updated all the labels in the adapter classes to include the `%s` including the WordPress Adapter

**Comment by jkphl** [comment]
@xwolfde Vielleicht nochmal kurz zur Erklärung:

1. Auf der untersten Ebene (`Foundations`-Verzeichnis) sind Suchmaschinen implementiert. Hier liegt die technische Funktionalität.
2. Auf der nächsten Ebene (`Adapters`) sind konkrete Implementierungen dieser Foundations definiert. Dort werden Labels für die Oberfläche angegeben.
3. Nur, wenn der Label einen `sprintf`-Platzhalter enthält, wird im Frontend ein Link integriert. Im Moment wird dir das Page-ID-Feld im Backend **immer** gezeigt, auch wenn dieser Wert (labelabhängig) nicht verwertet wird.

Wir könnten evtl. dafür sorgen, dass das ID-Feld im Backend nur angezeigt wird, wenn der Label ein Link überhaupt vorsieht, das macht die Sache aber etwas komplexer.
