### ISSUE TITLE
WCAG 1.3.1 Info und Beziehungen 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#44]
Nicht unterscheidbare Landmarks.
Im Deialog-bereich ist keine aria-labeledby für die Überschrift angegeben

**Comment by jkphl** [comment]
@xwolfde In welchem Zustand bzw. für welche Landmark konkret fehlt die Bezeichnung? 

![Screenshot](https://user-images.githubusercontent.com/4446936/52138015-5069ed00-264c-11e9-955a-8b1a1543f303.jpg)

**Comment by xwolfde** [comment]
Strange. Das war auf den Beta. ich check nochmal ob es da aktuell ist

**Comment by xwolfde** [comment]
Ich glaub ich weiß, wie die Fehlermeldung produziert wird, bin mir aber nun selbst nicht sicher, ob das ein tatsächlicher Fehler ist oder nur eine Überinterpretation:

In der Tat in dem Kontext der ```<dialog>```-Tag ein aria-labelledby.

 Was aber bemeckert wird vom Tool (hier der Siteimprove Validator, den es auch als Chrome-AddOn gibt)  ist gar nicht das ```<dialog>```, sondern der ```<header>```-Tag danach.


```html
<dialog id="search-header" class="search-header searchform" aria-labelledby="search-title" open="">        
      <form method="post" action="https://www.beta.wordpress.rrze.fau.de/wp-admin/admin-post.php" role="search">
            <input type="hidden" name="action" value="widget_form_submit">
            <header>
                <h2 id="search-title" class="screen-reader-text">Webauftritt durchsuchen</h2>
                <label for="headsearchinput">Geben Sie hier den Suchbegriff ein, um in diesem Webauftritt zu suchen:</label>
                <span class="searchicon"> </span>
                                <input id="headsearchinput" class="search-terms" type="text" value="" name="s" placeholder="Suchen nach..." autocomplete="off" tabindex="0">
                <input type="hidden" name="post_type[]" value="page">
<input type="hidden" name="post_type[]" value="post">
                <input type="submit" id="searchsubmit" value="Finden" tabindex="2">
            </header>
	    <div id="search-panel" class="search-panel" hidden="">
    ...
             </div>
        </form>
    </dialog>
```

**Comment by jkphl** [comment]
@xwolfde 

1. Was ist die konkrete Fehlermeldung?
2. Ich bin aus dem Stand heraus jetzt nicht sicher, ob das nicht sogar vor dem Umbau schon so war, oder ob wir den `<header>` hier eingeführt haben?!

**Comment by xwolfde** [comment]
Siehe da:
![suche-dialog-landmarks](https://user-images.githubusercontent.com/1070669/52335973-01350b00-2a04-11e9-9739-02575a88866d.jpg)

**Comment by xwolfde** [comment]
Ich tendiere selbst dazu zu sagen, dass es ein "false positive" ist. Denn eigentlich ist das dialog ja hierarchisch über den header. Und daher sollte sich das doch vererben. 
ich bin mir nur nicht sicher. Ggf. die Frage mal in der Szene ansprechen?

**Comment by kerstinp** [comment]
Ich wüsste nicht, was es auftragen sollte, wenn man dem header eine weitere Beschreibung zufügt. Was sollte da sinnvollerweise an mehr Information drin stehen, was nicht ohnehin schon vermittelt wird.

Es stellt sich mir eher die Frage, ob das Header-Element selber hier wirklich passt.

"A header typically contains a _group_ of introductory or navigational aids" (https://www.w3.org/TR/html50/sections.html#the-header-element)

**Comment by xwolfde** [comment]
Hab jetzt einfach das labeledby auch in header eingefügt.
