### ISSUE TITLE
Sprachcode in Adaptern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#6]
Bei den Adaptern der Sprachcodes sind die Labels, Namen und der Text zur Verlinkung einer Erklärung als Const-Values gegeben. 
Das ist bei der variablen Sprachausgabe nicht gut. Die Namen sollten auch abhängig von der verwendeten Sitesprache sein können.

**Comment by cowglow** [comment]
I think this also related to the changed we made to close #13
