### ISSUE TITLE
Probleme mit Label und Text

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-search#9]
Angenommen wir haben zwei verschiedene Google Suchen, oder gar mehr, die auch andere Domains durchsuchen. Die aber auf dieselbe Engine beruhen und nur unterschiedliche GCSE Ids haben
In dem Fall haben wir Probleme mit dem was wir uns bei den Labels ausgedacht haben: Die Labels wären gleich und man könnte die unterschiedlichen Suchen nicht voneinander unterscheiden.

Zudem haben wir das Problem mit dem Sprachen, siehe #6 

Ich glaube, wir sollten daher in der nächsten Phase des Projekts doch da nochmal rangehen.

**Comment by cowglow** [comment]
Right,
I've updated the Adapters classes to return a string directly from the function instead of the constant value. 
```
public static function getName(): string
    {
        return __('Google1 FAU Search', 'rrze-search');
    }

    public static function getLabel(): string
    {
        return __('Google FAU CS%s','rrze-search');
    }

    public static function getLinkLabel(): string
    {
        return __('READ FAU\'s Instructions', 'rrze-search');
    }
```

**Comment by jkphl** [comment]
@cowglow Not sure if this solves the issue that @xwolfde described. We might need multiple `Adapters` for a particular `Foundation` (e.g. Google Search), with individual configurations (GCSE IDs, so they must not be hardcoded), and maybe even different text labels in different WordPress instances, in multiple languages. I think things might have to be more configurable.
